---
title: "hw-2_notebook.qmd"
author: "Matin Borhani"
format: pdf
editor: visual
---

```{r}

#Q1.
lord_data<-readr::read_csv("lord-of-the-rings-trilogy.csv")

#Q2. The occasional and inconsistent use of capital letters. Also in tidy data we 
#usually have species, sex, and the number of observation (count),
#in seperate columns instead of giving them their own columns and 
#having them as seperate variables. 
#This also leads to a single column to have more than one type of data. 
#for example "elf-female" tells us about both elf and female and this is not tidy.
#Each Column should contain only one variable.

```

```{r}

#Q3.I would have 3 columns (race, sex, count) and 18 rows 
#(6 rows for each movie becuase we have 3 species/races that each consist of 
#male and female)

```

```{r}
#Q1A. Column names: "race", "sex", "count"
```

```{r}
lord_data_tidy_s2 <- lord_data |>
  tidyr::pivot_longer(c('elf_female', 'elf_male', 'Hobbit_female', 'hobbit_Male', 
                        'man_Female',
                'Man_male'),
    names_to = "race_sex",
    values_to = "count", 
    values_drop_na = TRUE)

print(lord_data_tidy_s2)


```

```{r}
lord_data_tidy_s2 |>
  dplyr::count(race_sex)

#Here I can see that each race_sex data point repeats 3 times in each of the 3 movies 
#so in total I should have 18 rows total.

```

```{r}
lord_data_tidy_s4 <- lord_data_tidy_s2 |>
   tidyr::separate(race_sex, c("race", "sex"), sep = "_")

lord_data_tidy_s4
```

```{r}
#Q2B
  male_hobbits_words_spoken <-dplyr::filter(lord_data_tidy_s4, race == "hobbit" 
                                            & sex == "male")
  male_hobbits_words_spoken
  
  dplyr::summarise(male_hobbits_words_spoken, sum_words = sum(count))

```

```{r}
#Q2BCONTINUED
  
  female_elf_words_spoken <-dplyr::filter(lord_data_tidy_s4, race == "elf" & sex
                                          == "female")
 
  female_elf_words_spoken
  
  dplyr::summarise(female_elf_words_spoken, sum_words = sum(count))
  
  
  male_elf_words_spoken <-dplyr::filter(lord_data_tidy_s4, race == "elf" 
                                        & sex == "male")
 
  male_elf_words_spoken
  
  dplyr::summarise(male_elf_words_spoken, sum_words = sum(count))
```

```{r}
library(stringr)

  lord_data_tidy_s4 <- dplyr::mutate(lord_data_tidy_s4,
    race = str_to_lower(race),  # making race column to lowercase
    sex = str_to_lower(sex)     # making sex column to lowercase
  )
```

```{r}
#Q3B and Q4B

lord_data_nosex <-lord_data_tidy_s4
lord_data_nosex <- dplyr::select(lord_data_tidy_s4, movie, race, count)

lord_data_nosex

#"Hobbit" in the movie "fellow ship of the king" and "man" in "return of the king" 
#seem to be dominant race speaking words in those movies.

#Therefore the number of words spoken by the dominant race does depend on the race
```
